version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: commission_calculator
    volumes:
      - .:/var/www
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    command: ["composer", "test"]